export const AC_TABLES = {
  ac_deals: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "title", type: "STRING" },
    { name: "value", type: "FLOAT64" },
    { name: "currency", type: "STRING" },
    { name: "status", type: "INT64" },
    { name: "contact_id", type: "STRING" },
    { name: "organization_id", type: "STRING" },
    { name: "stage_id", type: "STRING" },
    { name: "pipeline_id", type: "STRING" },
    { name: "owner_id", type: "STRING" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "next_action_date", type: "TIMESTAMP" },
    { name: "next_contact_date", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_deal_cf_meta: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "field_label", type: "STRING" },
    { name: "field_type", type: "STRING" },
    { name: "is_required", type: "BOOL" },
    { name: "is_form_visible", type: "BOOL" },
    { name: "display_order", type: "INT64" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_deal_cf_data: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "deal_id", type: "STRING" },
    { name: "custom_field_id", type: "STRING" },
    { name: "field_value", type: "STRING" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
};
