export const AC_TABLES = {
  ac_deals: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "title", type: "STRING" },
    { name: "value", type: "FLOAT64" },
    { name: "currency", type: "STRING" },
    { name: "status", type: "INT64" },
    { name: "is_disabled", type: "BOOL" },
    { name: "contact_id", type: "STRING" },
    { name: "organization_id", type: "STRING" },
    { name: "stage_id", type: "STRING" },
    { name: "pipeline_id", type: "STRING" },
    { name: "owner_id", type: "STRING" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "next_action_date", type: "TIMESTAMP" },
    { name: "next_contact_date", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_deal_cf_meta: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "field_label", type: "STRING" },
    { name: "field_type", type: "STRING" },
    { name: "is_required", type: "BOOL" },
    { name: "is_form_visible", type: "BOOL" },
    { name: "display_order", type: "INT64" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_deal_cf_data: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "deal_id", type: "STRING" },
    { name: "custom_field_id", type: "STRING" },
    { name: "field_value", type: "STRING" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_tags: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "name", type: "STRING" },
    { name: "description", type: "STRING" },
    { name: "tag_type", type: "STRING" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_contact_tags: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "contact_id", type: "STRING" },
    { name: "tag_id", type: "STRING" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_contact_cf_meta: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "title", type: "STRING" },
    { name: "perstag", type: "STRING" },
    { name: "field_type", type: "STRING" },
    { name: "is_required", type: "BOOL" },
    { name: "is_visible", type: "BOOL" },
    { name: "display_order", type: "INT64" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_contact_cf_data: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "contact_id", type: "STRING" },
    { name: "field_id", type: "STRING" },
    { name: "field_value", type: "STRING" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_lists: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "name", type: "STRING" },
    { name: "stringid", type: "STRING" },
    { name: "subscription_count", type: "INT64" },
    { name: "created_timestamp", type: "TIMESTAMP" },
    { name: "updated_timestamp", type: "TIMESTAMP" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
  ac_contact_lists: [
    { name: "id", type: "STRING", mode: "REQUIRED" },
    { name: "contact_id", type: "STRING" },
    { name: "list_id", type: "STRING" },
    { name: "status", type: "INT64" },
    { name: "subscription_date", type: "TIMESTAMP" },
    { name: "unsubscription_date", type: "TIMESTAMP" },
    { name: "first_name", type: "STRING" },
    { name: "last_name", type: "STRING" },
    { name: "ip4_sub", type: "STRING" },
    { name: "form_id", type: "STRING" },
    { name: "synced_at", type: "TIMESTAMP", mode: "REQUIRED" },
  ],
};
